
services:
  app:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - temporal
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
      TEMPORAL_ADDRESS: temporal:7233
    command : sh -c "sleep 30 && npm run dev"

  worker:
    build: .
    volumes:
     - .:/app
     - /app/node_modules
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    command: sh -c "sleep 30 && npm run worker"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  temporal:
    image: temporalio/auto-setup:latest
    ports:
      - "7233:7233"
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: